{
  "formatVersion": "1.1",
  "component": {
    "group": "uz.myid.sdk.capture",
    "module": "myid-3d-capture-sdk",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "myid-3d-capture-sdk-1.0.2.aar",
          "url": "myid-3d-capture-sdk-1.0.2.aar",
          "size": 4946705,
          "sha512": "132d5e45d1610a2f991b03746754843651279ad852e35ab6a770fb03bda3418e19875727ddd84153683a79aee1c975a53b18170ab783a3a2cd047a1b43df3fce",
          "sha256": "80f0fc665f19ac7f77dada5de886c8f794883c6068ee05100e64e63223c56fd1",
          "sha1": "54d3df0b245d4a3682d2d574d2ab21b6e3321c4d",
          "md5": "d0bc5251d7e75a162b8e9b43a8768d0c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-alpha04"
          }
        },
        {
          "group": "com.google.android.recaptcha",
          "module": "recaptcha",
          "version": {
            "requires": "18.5.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-mlkit-face-detection",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "face-mesh-detection",
          "version": {
            "requires": "16.0.0-beta2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-mlkit-text-recognition",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-mlkit-barcode-scanning",
          "version": {
            "requires": "18.3.0"
          }
        },
        {
          "group": "uz.myid.sdk.capture",
          "module": "myid-capture-sdk-core",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "myid-3d-capture-sdk-1.0.2.aar",
          "url": "myid-3d-capture-sdk-1.0.2.aar",
          "size": 4946705,
          "sha512": "132d5e45d1610a2f991b03746754843651279ad852e35ab6a770fb03bda3418e19875727ddd84153683a79aee1c975a53b18170ab783a3a2cd047a1b43df3fce",
          "sha256": "80f0fc665f19ac7f77dada5de886c8f794883c6068ee05100e64e63223c56fd1",
          "sha1": "54d3df0b245d4a3682d2d574d2ab21b6e3321c4d",
          "md5": "d0bc5251d7e75a162b8e9b43a8768d0c"
        }
      ]
    }
  ]
}
